# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
use_frameworks!

target 'TwitterABTest' do
  pod 'SDWebImage', '~>3.6'
  pod 'DOFavoriteButton'
  pod 'ABKit', path: '../'
end
